name: Deploy DBT to BigQuery

on:
  workflow_call:
    secrets:
      BQ_KEYFILE_JSON:
        required: true
      BQ_PROJECT:
        required: true
      BQ_DATASET:
        required: true
      BQ_DATASET_PD:
        required: true
      BQ_PRIVATE_KEY:
        required: true
      BQ_PRIVATE_KEY_ID: 
        required: true
      BQ_CLIENT_EMAIL: 
        required: true
      BQ_CLIENT_ID: 
        required: true
      BQ_AUTH_URI: 
        required: true
      BQ_TOKEN_URI: 
        required: true
      BQ_AUTH_PROVIDER_X509_CERT_URL: 
        required: true
      BQ_CLIENT_X509_CERT_URI: 
        required: true

env:
  BQ_PROJECT: ${{ secrets.BQ_PROJECT }}
  BQ_DATASET: ${{ secrets.BQ_DATASET }}
  BQ_DATASET_PD: ${{ secrets.BQ_DATASET_PD }}
  BQ_KEYFILE_JSON: ${{ secrets.BQ_KEYFILE_JSON }}
  BQ_LOCATION: ${{ secrets.BQ_LOCATION }}
  BQ_PRIVATE_KEY: ${{ secrets.BQ_PRIVATE_KEY }}
  BQ_PRIVATE_KEY_ID: ${{ secrets.BQ_PRIVATE_KEY_ID }}
  BQ_CLIENT_EMAIL: ${{ secrets.BQ_CLIENT_EMAIL }}
  BQ_CLIENT_ID: ${{ secrets.BQ_CLIENT_ID }}
  BQ_AUTH_URI: ${{ secrets.BQ_AUTH_URI }}
  BQ_TOKEN_URI: ${{ secrets.BQ_TOKEN_URI }}
  BQ_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.BQ_AUTH_PROVIDER_X509_CERT_URL }}
  BQ_CLIENT_X509_CERT_URI: ${{ secrets.BQ_CLIENT_X509_CERT_URI }}

jobs:
  validate_deploy:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install required packages
        run: |
          python -m pip install --upgrade pip

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: ${{ secrets.BQ_KEYFILE_JSON }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.BQ_PROJECT }}

      - name: Checkout dbt-common repository
        uses: actions/checkout@v3
        with:
          repository: endrit-berisha/dbt-common
          path: dbt-common

      - name: Validate PD BQ-DBT
        id: validate_pre_deployment
        if: github.event_name == 'pull_request'
        run: |
          echo "DBT changes detected. Proceeding with pre-deployment."
          pip install -r dbt-common/requirements.txt
          python dbt-common/pd_db_manager.py \
              --project_id=${{ secrets.BQ_PROJECT }} \
              --dataset_id='${{ secrets.BQ_DATASET_PD }}' \
              --credentials_json='${{ secrets.BQ_KEYFILE_JSON }}' \
              --dbt_path='./dbt' \
              --dbt_target="pd"

      - name: Deploy BQ-DBT
        id: deployment
        if: github.event_name != 'pull_request'
        run: |
          echo "DBT changes detected. Proceeding with deployment."
          pip install -r dbt-common/requirements.txt
          python dbt-common/pd_db_manager.py \
              --project_id='${{ secrets.BQ_PROJECT }}' \
              --dataset_id='${{ secrets.BQ_DATASET }}' \
              --credentials_json='${{ secrets.BQ_KEYFILE_JSON }}' \
              --dbt_path='./dbt' \
              --dbt_target='prod'

      - name: Delete PD BQ Database
        if: always()
        run: |
          pip install -r dbt-common/requirements.txt
          python dbt-common/pd_db_manager.py \
            --project_id=${{ secrets.BQ_PROJECT }} \
            --dataset_id='${{ secrets.BQ_DATASET_PD }}' \
            --credentials_json='${{ secrets.BQ_KEYFILE_JSON }}' \
            --dbt_path=./dbt \
            --dbt_target="pd" \
            --cleanup
